from typing import Callable

def cleanup() -> None: ...
def upload_model(path_to_model: str, print: Callable = ...): ...
def validate_model(
    path_to_model: str, print: Callable = ..., local_repo: str | None = None
): ...
