from typing import Callable, Optional

def cleanup() -> None: ...
def upload_model(path_to_model: str, print: Callable = ...): ...
def validate_model(
    path_to_model: str, print: Callable = ..., local_repo: Optional[str] = None
): ...
